-- Alter Enterprises table to add missing columns
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS user_id INTEGER;
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS name VARCHAR;
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS industry VARCHAR;
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS founded_date DATE;
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS website VARCHAR;
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS status VARCHAR DEFAULT 'active';
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS company_size VARCHAR;
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS revenue NUMERIC;
ALTER TABLE "Enterprises" ADD COLUMN IF NOT EXISTS location VARCHAR;